# -*- coding: utf-8 -*-
"""Look.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18K4QcTLM_I5nCRA2DEZIxI0v413R3X95
"""

def look_right_first_fixed(queue, start):
    path = [start]
    total_distance = 0
    current = start

    # Split requests into right and left
    right = sorted([r for r in queue if r >= start])
    left = sorted([r for r in queue if r < start], reverse=True)

    # 1. Serve right requests first
    for req in right:
        total_distance += abs(current - req)
        current = req
        path.append(req)

    # 2. Reverse direction and serve left requests
    for req in left:
        total_distance += abs(current - req)
        current = req
        path.append(req)

    return total_distance, path


queue = [98, 183, 37, 122, 14, 124, 65, 67]
start = 53

distance, path = look_right_first_fixed(queue, start)

print("Path:", path)
print("Total cylinder movement:", distance)